version: "2.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: docker-slurm
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: docker-slurm
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  c1:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c2:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M
      
  c3:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c3
    container_name: c3
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c4:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c4
    container_name: c4
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c5:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c5
    container_name: c5
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c6:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c6
    container_name: c6
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c7:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c7
    container_name: c7
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c8:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c8
    container_name: c8
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c9:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c9
    container_name: c9
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c10:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c10
    container_name: c10
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c11:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c11
    container_name: c11
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c12:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c12
    container_name: c12
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c13:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c13
    container_name: c13
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c14:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c14
    container_name: c14
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c15:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c15
    container_name: c15
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M

  c16:
    image: docker-slurm
    command: ["slurmd"]
    hostname: c16
    container_name: c16
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/nfs
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 200M


volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
